### ISSUE TITLE
Polymer 3.0 roadmap

### ISSUE THREAD

**Issue by leebickmtu** [predixdesignsystem/px-app-nav#110]
Not an issue so much as a question.

What is the roadmap looking like for the Predix UI components as far as Polymer 3.0 support as npm modules?

**Comment by evanjd** [comment]
We're keen on it, but there's no roadmap or ETA at this stage. Cleaning up issues and PRs on existing repos is the higher priority right now.

If/when we do it, I expect we'll copy vaadin's approach and maintain Polymer 2.x versions on github (w/ HTML Imports), and use modulizer to build and publish a Polymer 3.x version (w/ ES6 modules) whenever we do a release. This would allow us to maintain bower and npm packages in parallel.

Are you just curious or do you have some requirements/dependencies specific to Polymer 3.x?

**Comment by leebickmtu** [comment]
Working on an app with existing Polymer 2.x code base, and beginning initial look into porting to Polymer 3.x. Audited all our dependencies, Predix components and 1 other are the only packages without Polymer 3.x version in NPM.

So no immediate need but as of now Predix is pretty much the only roadblock for when we would want to switch.

**Comment by ergo** [comment]
Same here, all my work is now ES6 Modules, so anything lower than Polymer 3.x is a problem to maintain.

**Comment by ergo** [comment]
Any chance the system can be migrated with polymer modulizer? It simpliefied the process for me.
