### ISSUE TITLE
v2.3.1 - Width of app-nav-item is hard-coded, so background-color doesn't extend to width of app nav.

### ISSUE THREAD

**Issue by squidbe** [predixdesignsystem/px-app-nav#111]
## Expected behavior
In vertical [collapsed] mode, nav items and their associated background-color expand to width of app-nav.
v2.3.0:
<img width="240" alt="px-app-nav--2 3 0" src="https://user-images.githubusercontent.com/1664227/51875663-b851c800-231a-11e9-8d63-6d3bb961b32c.png">

## Actual behavior:
In vertical [collapsed] mode, nav item width is set to 23.33333rem.
(See `:host([collapsed]){width:23.33333rem}` in "**px-app-nav-item-styles.html**".)
v2.3.1:
<img width="240" alt="px-app-nav--2 3 1" src="https://user-images.githubusercontent.com/1664227/51875689-d0c1e280-231a-11e9-8a49-52e33bd8be63.png">

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
v2.3.1
Chrome/Firefox/Safari
Mac Sierra

**Comment by e-kag** [comment]
@squidbe I failed to reproduce this myself, neither with `collapseAll` nor `vertical`.

Could you provide an example of you `px-app-nav` item when you see this issue appear?

**Comment by squidbe** [comment]
@e-kag I'll get to that within the next couple of days, but you can see that the width is hard-coded to 23.33333rem -- do you know why it's hard-coded?

**Comment by e-kag** [comment]
@squidbe that was done as part of some design compliance work (https://github.com/predixdesignsystem/px-app-nav/issues/61).
