### ISSUE TITLE
In Overflow view, selected nav item's parent style should be updated.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-app-nav#51]
## Expected behavior:

When a sub-nav is present in the overflow, selecting a nav item in the sub-nav should not change the background color of the parent to "selected".
Per design, the background color of the parent should remain $grey2 not white.

## Environment:
App-Nav: Master/Latest Pull
Browser: Chrome

### Design Spec vs. Implementation

<img width="1278" alt="screen shot 2017-07-18 at 1 52 24 pm" src="https://user-images.githubusercontent.com/10835611/28340087-54327924-6bc3-11e7-8516-e50e488d764d.png">

/cc @davidrleonard

**Comment by e-kag** [comment]
Fixed in PR: https://github.com/predixdesignsystem/px-app-nav/pull/104

**Comment by arongraham-ge** [comment]
the collapsed nav works as it should. this is not an issue. i agree that it looks a little quirky when the expand "arrowhead" item is white and the parent item is white but it needs to be understood that the collapse "arrowhead" it not a menu item. its an indicator that tells the user that there is "more content under here"
the parent item when selected should still remain white.
to show why i think changing this to grey would be bad see the following gif

![2019-01-11_10-54-05](https://user-images.githubusercontent.com/32055826/51006766-7130ac80-1590-11e9-8019-02361bd71512.gif)

as you can see, when the user widens the browser window the menu expands and the "arrowhead" is hidden. when expanded the selected items parent is white. as per design system. but when collapsed it is grey. this will be very confusing to the user

closing issue as not required
