### ISSUE TITLE
Collapsed Nav updates: Pre-loader hover state and animation speed should be updated.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-app-nav#59]
## Behavior:

Tracking issue for 2 design related changes:

1. Currently in the collapsed nav, there is a hover state for the pre-loader; however, because of styles, hovering over the pre-loader will wash out the current color scheme.  Wade will be looking at the hover state styles to update them.
2.  Selecting the down arrow to open the nav animates he nav dropdown.  Wade would like to increase the speed of the animation and likes to get the speed adjusted. 
3. Pre-loader styles in dark theme may need to be revisited.

## Environment:

App-Nav: Master-7/18 evening Pull
Browsers: Chrome & Safari9

### Original State:

![screen shot 2017-07-19 at 2 39 37 pm](https://user-images.githubusercontent.com/10835611/28390738-30c97410-6c90-11e7-93fd-20d140998042.png)

### On Hover:

![screen shot 2017-07-19 at 2 39 31 pm](https://user-images.githubusercontent.com/10835611/28390757-3d732274-6c90-11e7-851c-21d1de89d5ad.png)

### Dark Theme pre-loader:

![screen shot 2017-07-26 at 10 27 06 am](https://user-images.githubusercontent.com/10835611/28634779-23c64fba-71ed-11e7-81c6-c639896c2a1d.png)

/cc @davidrleonard

**Comment by e-kag** [comment]
@arcpato it seems to me that `$grey6` can do the trick, but I need your verification:
![grey6](https://user-images.githubusercontent.com/20826874/50989659-cdc69580-14c4-11e9-834d-5340e9789768.gif)

`$grey5` seems to look better in default and hover state, but it gets washed out when clicked.
![grey5](https://user-images.githubusercontent.com/20826874/50989759-0ebeaa00-14c5-11e9-9411-bae4eed6ba75.gif)

**Comment by arcpato** [comment]
@e-kag I agree that it makes no sense to allow clicking on the item when it has not loaded, as it would have nowhere to navigate to. Are you able to disable the click and hover white the pre-loader state is active?

![screen shot 2019-01-10 at 2 41 28 pm](https://user-images.githubusercontent.com/6137443/51001805-193d6b80-14e6-11e9-993e-df97efb4ad47.png)

This is with `$gray5`

The navigation should not enter the pre-loader state with long labels, but when the label is being fetched.

**Comment by e-kag** [comment]
@arcpato In that case I will create another ticket handle:
1. Disabling hover and click when in pre-load state.
2. Correct the invocation of the pre-load state -- ie. the component **only** enters pre-load state when the label is not yet loaded.

Should the icon colour then be `$grey5`? Also, since you had chance to look at this ticket, do you have any input for points #2 and #3 in the in the first comment? I wouldn't make tackling this ticket sometime soon if you are able to shed some light on those points.

**Comment by arcpato** [comment]
1 & 3, Yes, pre-load color is $gray6 for the light theme, and $gray17 for dark theme. 
![screen shot 2019-01-10 at 3 14 40 pm](https://user-images.githubusercontent.com/6137443/51004237-9ff64680-14ee-11e9-8058-8372b8674d48.png)

2. For the animation, I have no context as to what Wade wanted to change or why, so unless we are seeing an issue I think we should not change it.

**Comment by e-kag** [comment]
Closing this issue, as:
**1**: is not valid, given that the pre-load state should not be interactive.
**2**: There seems to be no issue with the animation speed. If there is, we can open a separate issue to address it later.
**3**: Dark them style looks to be fine, we can open another issue later if not.
