### ISSUE TITLE
Minor updates needed to match the design.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-app-nav#61]
Minor updates may be needed to match the design:

1. Looks like the left padding in the sub-nav dropdown should have 50 px and it currently has 55px padding.
2. Default width of the nav-item should be adjusted to 320 rather than 290px.

## Environment:

App-Nav: Master-7/18 evening Pull
Browsers: Chrome & Safari9

### Subnav Padding
<img width="727" alt="screen shot 2017-07-19 at 3 47 06 pm" src="https://user-images.githubusercontent.com/10835611/28393123-fd7fdbb2-6c99-11e7-8352-0655523eb433.png">

### Nav-item width
<img width="1389" alt="screen shot 2017-07-19 at 4 02 06 pm" src="https://user-images.githubusercontent.com/10835611/28393540-20b67378-6c9c-11e7-9a9b-d1aa62ed5261.png">

/cc @davidrleonard

**Comment by e-kag** [comment]
Fixed in PR: https://github.com/predixdesignsystem/px-app-nav/pull/104
