### ISSUE TITLE
Demo page: drop down menu shows up at top of screen.

### ISSUE THREAD

**Issue by skistz** [predixdesignsystem/px-app-nav#71]
Chrome Version 60.0.3112.78 (Official Build) (64-bit)
-View AppNav in horizontal format
-Click on Assets
-Drop down shows up at the top of the screen under the grey bar

**Screenshot:**
![image](https://user-images.githubusercontent.com/25310251/28746435-170ada1a-7441-11e7-83a0-af619d692950.png)

**Comment by talimarcus** [comment]
Still trying to figure out exactly how to replicate it, but I keep seeing this:

![screen shot 2017-10-11 at 5 01 46 pm](https://user-images.githubusercontent.com/9092541/31473018-e93058d6-aea6-11e7-9e81-4b6cdc37b355.png)

Potentially related to the above issue

**Comment by randyaskin** [comment]
This may be a different issue but it sounds related so I'm chucking it here. On the demo site, the overflow button doesn't do anything (the dropdown doesn't appear at all, as far as I can tell), but if you spin it up locally outside of the site, it works fine.

**Comment by skistz** [comment]
Still happening.

![image](https://user-images.githubusercontent.com/25310251/36686331-e9acd80c-1ada-11e8-82b0-c875c300ad4f.png)

**Comment by alfaeddie** [comment]
@randyaskin I see the same behaviour, works fine when deployed locally.

When `scrollTop = 0`, the dropdown incorrectly calculates `top:0` despite the `vertical-align="top"` in `iron-dropdown`.
![image](https://user-images.githubusercontent.com/20826874/50792426-d11a1100-1279-11e9-89bf-23f0d8871b40.png)

If I scroll down it starts to positions correctly.
![image](https://user-images.githubusercontent.com/20826874/50792459-edb64900-1279-11e9-83e6-aa72540422d4.png)
