### ISSUE TITLE
px-app-nav horizontal mode works as collapsed, when transpiled for ES5

### ISSUE THREAD

**Issue by bharat-srinivasan** [predixdesignsystem/px-app-nav#78]
## Expected behavior
px-app-nav is displayed in horizontal mode.
## Actual behavior:
px-app-nav is displayed in collapsed mode.

## Steps to reproduce the problem:
1. Clone the repository https://github.com/PredixDev/px-app-nav.git
2. Do the necessary setup (Install npm and bower dependencies)
3. Run the command `npm run build`. This will generate a `build` directory with runnable demo code.
4. Launch the demo application from `build` directory. I used _http-server_ to launch it. `http-server build -p 8080 -o`

## Environment :
OS: Mac OS X El Capitan
Browser: Google Chrome
NPM: 5.4.2

## Screenshots:
![screen shot 2017-10-09 at 14 34 11](https://user-images.githubusercontent.com/15170423/31331579-84ab4cce-ad00-11e7-8e70-41a2c86ea1d5.png)

**Comment by mdwragg** [comment]
Hi,
Made you seeing any errors in the console? What if you use the Polymer CLI to serve it (this automatically transpiles)?

**Comment by mdwragg** [comment]
Autocorrect ‘are you seeing any errors’

**Comment by davidrleonard** [comment]
Found the issue. When our px-app-nav.scss is built into px-app-nav-styles.html it goes through a minifier. Then, when we run polymer build it runs another minifier on it. There's an `@apply --px-app-nav` line in px-app-nav.scss. 

Related issue: https://github.com/PolymerLabs/css-slam/issues/1

We'll work on getting a patch in to fix, it's a dependency version issue.

**Comment by talimarcus** [comment]
The css-slam dependency has been updated in polymer-cli, just waiting for the latest to be tagged.

**Comment by mdwragg** [comment]
@bharat-srinivasan - Google released the patched Polymer CLI 10 hours ago. We'll verify tomorrow and respond to this issue.

**Comment by davidrleonard** [comment]
FYI there's still a regression in the library used in polymer-cli. We've filed it in PolymerLabs/css-slam#15 and we'll update here when there's a fix.

**Comment by davidrleonard** [comment]
6fbdcc7 (v2.0.11) is a temporary fix while the upstream libraries fix this.

@bharat-srinivasan If you update your bower dependencies to get this version your problem should be fixed.

I'll leave this issue open for now to track the upstream css-slam issue (PolymerLabs/css-slam#15). We can revert this temporary fix when css-slam is updated.
