### ISSUE TITLE
App Nav Vertical Expanded View

### ISSUE THREAD

**Issue by nschexn** [predixdesignsystem/px-app-nav#81]
This is a feature request for the Vertical navigation to have an option style to be expanded by default above a certain breakpoint.  

Our use case is that we would like a desktop version to have the expanded style, and then collapse down to the icon only view at a smaller breakpoint size.  

Additionally, the expanded view should also take into consideration that the navigation would fill up a specific amount of space rather than floating over the content.

**Comment by davidrleonard** [comment]
We're working on this over in #82. We plan to ship this feature in the current quarter.

**Comment by insight123m** [comment]
Hi David,
When can we expect to have this shipped as I need to implement a toggle button for the vertical view of px-app-nav. Any pointers as to how to have the functionality just like the older px-app-nav wherein user can toggle the vertical layout using a hamburger icon ?

**Comment by davidrleonard** [comment]
This feature is currently in our backlog for this quarter. Should be shipped by or before the end of the quarter (next 2-3 months). Check back on this issue for updates when we ship this feature.

**Comment by e-kag** [comment]
@nschexn see release https://github.com/predixdesignsystem/px-app-nav/releases/tag/v3.0.0. 

There is a property `vertical-opened-at` than can open and close the vertical navigation based on the breakpoint size you've mentioned. As for the floating over content, I would suggest simply data-binding on the `vertical-opened` property of the `px-app-nav` element and adjusting the content placement. A good example of this can be seen in `px-app-nav-demo.html`: https://github.com/predixdesignsystem/px-app-nav/blob/fafbf68bed8217270cca484837e764fb19e040a8/demo/px-app-nav-demo.html#L278.
