### ISSUE TITLE
when pathPrefix property is added to the appNav component the selected menu item is not highlighting

### ISSUE THREAD

**Issue by mahesh-sanikommu** [predixdesignsystem/px-app-nav#87]
## Expected behavior and actual behavior:
when I select the menu Item, i should see the menu highlighted for selected item

## Steps to reproduce the problem:
Add **pathPrefix** property to the appNav component . 
 

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):   
Using     "px-app-nav": "^1.10.9"

## Screenshots (_optional, but very helpful_):

<img width="553" alt="screen shot 2017-12-22 at 2 08 59 pm" src="https://user-images.githubusercontent.com/27749064/34313733-34b30d5e-e722-11e7-974f-1d69a19d5459.png">

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
What value are you trying to use for `pathPrefix`? To me, it looks like your URL is incorrect - it should be `/propel/#services` instead of `propel#/services` I believe.

**Comment by mahesh-sanikommu** [comment]
My pathPrefix value is '/propel/#'.
Even though I set my url to /propel/#services it's not working for me.

**Comment by randyaskin** [comment]
I think you just want to use the default pathPrefix of `#`, which will cause `#services` to be appended to whatever URL is already being used by your application `whatever/propel/`.

**Comment by mahesh-sanikommu** [comment]
when i set that value to '#' the link for the tab is setting like 'http://localhost:3000/#services' you can find that in screenshot(left bottom). It should be 'http://localhost:3000/propel/#services'. So i set the pathPrefix value to '/propel/#'.

<img width="1440" alt="screen shot 2017-12-22 at 4 18 28 pm" src="https://user-images.githubusercontent.com/27749064/34315431-4408b3fa-e734-11e7-9a4e-6a42cd529058.png">
