### ISSUE TITLE
app-nav styling not being applied when item is toggled from hidden to shown.

### ISSUE THREAD

**Issue by scassella** [predixdesignsystem/px-app-nav#88]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Expected:
App-nav tab starts as hidden, is dynamically shown, and correct custom styles are applied.
Actual:
App-nav tab starts as hidden, and when dynamically shown the default styles are applied. 

## Steps to reproduce the problem:
Use px-app-nav, add custom styles, applied a class with "display: none !important;  visibility: hidden;" and programmatically removed class. (Default style persisted. Custom styles did not apply.)

After showing app-nav, if we call notifyResize(), the correct styles are added. 

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
component version: ^2.0.6, browser: Chrome version 63.0, Operating System: MAC OS Sierra version 10.12.6

## Screenshots (_optional, but very helpful_):

![screen shot 2018-01-23 at 2 09 43 pm](https://user-images.githubusercontent.com/25677280/35303567-42d1a65a-0047-11e8-8088-705cf3964766.png)

![screen shot 2018-01-23 at 2 09 51 pm](https://user-images.githubusercontent.com/25677280/35303555-35fa3744-0047-11e8-9d2b-e0e2e865b72a.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by e-kag** [comment]
@scassella Could you provide a code example, I am having trouble understanding your steps to reproduce. What is the use case you are trying to accomplish? 

Also, by "App-nav tab", do you mean the app-nav element?
